on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

name: Bench

jobs:
  bench:
    name: Build and Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout ğŸ›ï¸
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-bench
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain ğŸ›ï¸
        with:
          toolchain: nightly
          default: true
      - name: Benchmark ğŸš€
        run: cargo +nightly bench --all-features --workspace -- --output-format bencher | tee output.txt
      - uses: benchmark-action/github-action-benchmark@v1
        name: Store benchmark result
        with:
          tool: "cargo"
          output-file-path: output.txt
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
  sanitizer_bench:
    name: Bench with Sanitizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout ğŸ›ï¸
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-sanitizer-bench
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain ğŸ›ï¸
        with:
          components: rust-src
          toolchain: nightly
          default: true
      - uses: actions-rs/cargo@v1
        name: Bench with Address Sanitizer ğŸš€
        with:
          command: bench
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=address"
      - uses: actions-rs/cargo@v1
        name: Bench with Leak Sanitizer ğŸš€
        with:
          command: bench
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=leak"
      - uses: actions-rs/cargo@v1
        name: Bench with Memory Sanitizer ğŸš€
        with:
          command: bench
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=memory"
      - uses: actions-rs/cargo@v1
        name: Bench with Thread Sanitizer ğŸš€
        with:
          command: bench
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=thread"
