on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'reason to trigger this build'
        required: false

name: CI with Sanitizer

jobs:
  sanitizer_test:
    name: Test with Sanitizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout ğŸ›ï¸
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-sanitizer-test
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain ğŸ›ï¸
        with:
          components: rustfmt, clippy, rust-src
          toolchain: nightly
          default: true
      - uses: actions-rs/cargo@v1
        name: Running Tests with Address Sanitizer ğŸš€
        with:
          command: test
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=address"
      - uses: actions-rs/cargo@v1
        name: Running Tests with Leak Sanitizer ğŸš€
        with:
          command: test
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=leak"
      - uses: actions-rs/cargo@v1
        name: Running Tests with Memory Sanitizer ğŸš€
        with:
          command: test
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=memory"
      - uses: actions-rs/cargo@v1
        name: Running Tests with Thread Sanitizer ğŸš€
        with:
          command: test
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=thread"
  sanitizer_bench:
    name: Bench with Sanitizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout ğŸ›ï¸
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-sanitizer-bench
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain ğŸ›ï¸
        with:
          components: rust-src
          toolchain: nightly
          default: true
      - uses: actions-rs/cargo@v1
        name: Bench with Address Sanitizer ğŸš€
        with:
          command: bench
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=address"
      - uses: actions-rs/cargo@v1
        name: Bench with Leak Sanitizer ğŸš€
        with:
          command: bench
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=leak"
      - uses: actions-rs/cargo@v1
        name: Bench with Memory Sanitizer ğŸš€
        with:
          command: bench
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=memory"
      - uses: actions-rs/cargo@v1
        name: Bench with Thread Sanitizer ğŸš€
        with:
          command: bench
          args: --all-features -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=thread"