on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  
name: CI with Sanitizer

jobs:
  skl_test:
    name: Test Skiplist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout ğŸ›ï¸
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-sanitizer-test
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain ğŸ›ï¸
        with:
          components: rustfmt, clippy, rust-src
          toolchain: nightly
          default: true
      - uses: actions-rs/cargo@v1
        name: Running Tests with Address Sanitizer ğŸš€
        with:
          command: test
          args: --all-features -p skiplist -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=address"
      - uses: actions-rs/cargo@v1
        name: Running Tests with Leak, Memory and Thread Sanitizer ğŸš€
        with:
          command: test
          args: --all-features -p skiplist -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=leak,memory,thread"
  skl_bench:
    name: Build and Bench Skiplist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout ğŸ›ï¸
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-sanitizer-bench
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain ğŸ›ï¸
        with:
          components: rust-src
          toolchain: nightly
          default: true
      - uses: actions-rs/cargo@v1
        name: Bench with Address Sanitizer ğŸš€
        with:
          command: bench
          args: --all-features -p skiplist -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=address"
      - uses: actions-rs/cargo@v1
        name: Bench with Leak, Memory and Thread Sanitizer ğŸš€
        with:
          command: bench
          args: --all-features -p skiplist -Zbuild-std --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-Zsanitizer=leak,memory,thread"